import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  DoorOpen,
  Download,
  Eye,
  FileText,
  Filter,
  Home,
  Key,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Moon,
  MoreHorizontal,
  Plus,
  Printer,
  Search,
  Settings,
  Shield,
  Sun,
  User,
  UserCheck,
  UserCog,
  Users,
  X,
  XCircle,
  Building2,
  ClipboardList,
  History,
  Bell,
  CheckCircle2,
} from "lucide-react"

export const Icons = {
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bell: Bell,
  building: Building2,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clipboardList: ClipboardList,
  clock: Clock,
  creditCard: CreditCard,
  doorOpen: DoorOpen,
  download: Download,
  eye: Eye,
  fileText: FileText,
  filter: Filter,
  history: History,
  home: Home,
  key: Key,
  laptop: Laptop,
  layoutDashboard: LayoutDashboard,
  loader: Loader2,
  logOut: LogOut,
  mail: Mail,
  menu: Menu,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  printer: Printer,
  search: Search,
  settings: Settings,
  shield: Shield,
  sun: Sun,
  user: User,
  userCheck: UserCheck,
  userCog: UserCog,
  users: Users,
  x: X,
  xCircle: XCircle,
}

export type IconKey = keyof typeof Icons

export function getAssetIcon(iconName?: string) {
  const iconMap: Record<string, keyof typeof Icons> = {
    "door-open": "doorOpen",
    key: "key",
    laptop: "laptop",
    "credit-card": "creditCard",
  }

  return Icons[iconMap[iconName || ""] || "fileText"]
}
